export const heroSlides = [
  {
    id: 1,
    image: "/images/hero-1.webp",
    title: "Металлопрокат оптом и в розницу",
    subtitle: "Более 336 наименований: трубы, листы, арматура, уголки, швеллеры",
    buttonText: "Перейти в каталог",
    buttonHref: "/catalog",
  },
  {
    id: 2,
    image: "/images/hero-2.webp",
    title: "Доставка по Москве и МО",
    subtitle: "Быстрая доставка со склада. Самовывоз с базы.",
    buttonText: "Условия доставки",
    buttonHref: "/delivery",
  },
  {
    id: 3,
    image: "/images/hero-3.webp",
    title: "Всё для строительства из металла",
    subtitle: "Профнастил, трубы профильные, листы, метизы — всё в наличии",
    buttonText: "Связаться с нами",
    buttonHref: "/contacts",
  },
];

export const categories = [
  { id: "1", name: "Трубы профильные", slug: "truby-profilnye-kvadrat", productCount: 39, icon: "box" },
  { id: "2", name: "Трубы прямоугольные", slug: "truby-profilnye-pryamougolnye", productCount: 41, icon: "box" },
  { id: "3", name: "Трубы ВГП", slug: "truby-vgp", productCount: 12, icon: "cylinder" },
  { id: "4", name: "Трубы оцинкованные", slug: "truby-ocink", productCount: 12, icon: "cylinder" },
  { id: "5", name: "Трубы электросварные", slug: "truby-elektrosvarnye", productCount: 8, icon: "cylinder" },
  { id: "6", name: "Арматура", slug: "armatura", productCount: 10, icon: "construction" },
  { id: "7", name: "Уголок", slug: "ugolok", productCount: 16, icon: "angle" },
  { id: "8", name: "Швеллер", slug: "shveller", productCount: 11, icon: "beam" },
  { id: "9", name: "Балка", slug: "balka", productCount: 12, icon: "beam" },
  { id: "10", name: "Листы", slug: "listy", productCount: 44, icon: "sheet" },
  { id: "11", name: "Профнастил", slug: "profnastil", productCount: 15, icon: "roof" },
  { id: "12", name: "Полоса", slug: "polosa", productCount: 15, icon: "minus" },
  { id: "13", name: "Квадрат", slug: "kvadrat", productCount: 11, icon: "square" },
  { id: "14", name: "Прут", slug: "prut", productCount: 8, icon: "minus" },
  { id: "15", name: "Заглушки", slug: "zaglushki", productCount: 29, icon: "circle" },
  { id: "16", name: "Отводы", slug: "otvody", productCount: 20, icon: "corner" },
  { id: "17", name: "Петли", slug: "petli", productCount: 13, icon: "link" },
  { id: "18", name: "Задвижки", slug: "zadvizhki", productCount: 8, icon: "lock" },
  { id: "19", name: "Саморезы", slug: "samorezy", productCount: 8, icon: "screw" },
  { id: "20", name: "Проволока", slug: "provoloka", productCount: 1, icon: "cable" },
];

export const popularProducts = [
  {
    id: "1",
    name: "Труба профильная 60х40х2 Северсталь",
    slug: "truba-profilnaya-60x40x2",
    code: "00034",
    price: 200,
    specialPrice: 0,
    category: "Трубы прямоугольные",
    categorySlug: "truby-profilnye-pryamougolnye",
    image: null,
    isHit: true,
    isNew: false,
    unit: "м",
  },
  {
    id: "2",
    name: "Арматура А500C ф 12 Северсталь",
    slug: "armatura-a500c-f12",
    code: "00256",
    price: 40,
    specialPrice: 0,
    category: "Арматура",
    categorySlug: "armatura",
    image: null,
    isHit: true,
    isNew: false,
    unit: "м",
  },
  {
    id: "3",
    name: "Уголок 50х50х5 Северсталь",
    slug: "ugolok-50x50x5",
    code: "00004",
    price: 245,
    specialPrice: 0,
    category: "Уголок",
    categorySlug: "ugolok",
    image: null,
    isHit: true,
    isNew: false,
    unit: "м",
  },
  {
    id: "4",
    name: "Профнастил С20 1100х2000 коричневый",
    slug: "profnastil-c20-korichnevyj",
    code: "00168",
    price: 1050,
    specialPrice: 0,
    category: "Профнастил",
    categorySlug: "profnastil",
    image: null,
    isHit: true,
    isNew: false,
    unit: "шт",
  },
  {
    id: "5",
    name: "Швеллер №10 Северсталь",
    slug: "shveller-10",
    code: "00073",
    price: 515,
    specialPrice: 0,
    category: "Швеллер",
    categorySlug: "shveller",
    image: null,
    isHit: false,
    isNew: true,
    unit: "м",
  },
  {
    id: "6",
    name: "Лист стальной 3мм 1.25x2.5 х/к",
    slug: "list-stalnoj-3mm-xk",
    code: "00247",
    price: 5800,
    specialPrice: 5200,
    category: "Листы",
    categorySlug: "listy",
    image: null,
    isHit: true,
    isNew: false,
    unit: "шт",
  },
  {
    id: "7",
    name: "Труба электросварная 57х3 Северсталь",
    slug: "truba-elektrosvarnaya-57x3",
    code: "00001",
    price: 265,
    specialPrice: 0,
    category: "Трубы электросварные",
    categorySlug: "truby-elektrosvarnye",
    image: null,
    isHit: false,
    isNew: true,
    unit: "м",
  },
  {
    id: "8",
    name: "Балка двутавровая 20 Северсталь",
    slug: "balka-dvutavrovaya-20",
    code: "00240",
    price: 1550,
    specialPrice: 0,
    category: "Балка",
    categorySlug: "balka",
    image: null,
    isHit: true,
    isNew: false,
    unit: "м",
  },
];

export const contactInfo = {
  phone: "+7 (495) 760-55-39",
  phoneRaw: "+74957605549",
  email: "info@metallider.ru",
  address: "Реутов, ш. Автомагистраль Москва — Нижний Новгород, 1",
  warehouse: "Склад МеталлЛидер",
  workingHours: "Пн-Сб: 8:00 — 18:00",
  workingDays: "Пн-Сб: 8:00 — 18:00",
  mapUrl: "https://yandex.com/maps/-/CPuSEGzR",
};
